build_platform: {osx_arm64: osx_64}
conda_forge_output_validation: true
provider: {linux_aarch64: azure, linux_ppc64le: azure}
test_on_native_only: true
azure:
  settings_osx:
    pool:
      vmImage: macOS-10.14
github:
  branch_name: main
  tooling_branch_name: main
